{
  "formatVersion": "1.1",
  "component": {
    "group": "net.kyori",
    "module": "adventure-key",
    "version": "4.17.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "net.kyori",
          "module": "adventure-bom",
          "version": {
            "requires": "4.17.0-SNAPSHOT"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "net.kyori",
          "module": "examination-api",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "net.kyori",
          "module": "examination-string",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "24.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "adventure-key-4.17.0-SNAPSHOT.jar",
          "url": "adventure-key-4.17.0-SNAPSHOT.jar",
          "size": 11269,
          "sha512": "cde18204280e65197af03bfd7313d8395086599d36ef2c80ba9b9da77d8e3fedf73ba09c1123c62686f009131dc72d57a5079f4a87a56e0a833ed77dee640ba8",
          "sha256": "1ce91e3e04bd0a992356b154d179cec0105a55867b17cc3fcb713f8b18a3aa37",
          "sha1": "3689efdc9b3773dcb545613819c17cced7bdf69d",
          "md5": "944cc1707eebe2f951ba679fc5fbff5e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.kyori",
          "module": "adventure-bom",
          "version": {
            "requires": "4.17.0-SNAPSHOT"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "net.kyori",
          "module": "examination-api",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "net.kyori",
          "module": "examination-string",
          "version": {
            "requires": "1.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "adventure-key-4.17.0-SNAPSHOT.jar",
          "url": "adventure-key-4.17.0-SNAPSHOT.jar",
          "size": 11269,
          "sha512": "cde18204280e65197af03bfd7313d8395086599d36ef2c80ba9b9da77d8e3fedf73ba09c1123c62686f009131dc72d57a5079f4a87a56e0a833ed77dee640ba8",
          "sha256": "1ce91e3e04bd0a992356b154d179cec0105a55867b17cc3fcb713f8b18a3aa37",
          "sha1": "3689efdc9b3773dcb545613819c17cced7bdf69d",
          "md5": "944cc1707eebe2f951ba679fc5fbff5e"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.kyori",
          "module": "adventure-bom",
          "version": {
            "requires": "4.17.0-SNAPSHOT"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "net.kyori",
          "module": "examination-api",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "net.kyori",
          "module": "examination-string",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "24.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "adventure-key-4.17.0-SNAPSHOT-javadoc.jar",
          "url": "adventure-key-4.17.0-SNAPSHOT-javadoc.jar",
          "size": 107386,
          "sha512": "75dcd3cffede322a860f4ffbb191b644767134048efeb071224d173e262bf316dc43dd611d56c0cf4f32e048dade3df6b5943c215342f08b0ebe81059059295c",
          "sha256": "49a51192a6d108e2ab422ca0d40e9058aae90db50746845417c5728280d2aa80",
          "sha1": "1e957ba6904411d543c4dcd5017d04fd5cabb39d",
          "md5": "8a4f8bfa08426aad0b4bd1ab742a75a0"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "adventure-key-4.17.0-SNAPSHOT-sources.jar",
          "url": "adventure-key-4.17.0-SNAPSHOT-sources.jar",
          "size": 13406,
          "sha512": "41858078e44d0b499b14302c85243c96352f411aa6cd18f01a4a61974a6246711d1bfe99d86f2c9b60b91c80be9f393f6be42a3690fcfadec9fca5f3b3d36dd8",
          "sha256": "520910a23772b2508eea97378979b2a162a00ab8d0952afb16c0e0203202b498",
          "sha1": "08516fad07f351850dc807ef692257449eaf7831",
          "md5": "a6f6e91606be50462bdda8dcd6ab685d"
        }
      ]
    }
  ]
}
