{
  "formatVersion": "1.1",
  "component": {
    "group": "net.kyori",
    "module": "adventure-api",
    "version": "4.17.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "net.kyori",
          "module": "adventure-bom",
          "version": {
            "requires": "4.17.0-SNAPSHOT"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "net.kyori",
          "module": "adventure-key",
          "version": {
            "requires": "4.17.0-SNAPSHOT"
          }
        },
        {
          "group": "net.kyori",
          "module": "examination-api",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "net.kyori",
          "module": "examination-string",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "24.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "adventure-api-4.17.0-SNAPSHOT.jar",
          "url": "adventure-api-4.17.0-SNAPSHOT.jar",
          "size": 399820,
          "sha512": "5df8e5a3fa0f6c68a31c3bf0d9a8c3f766eb72da18f382aebcc9ce79fa895bfd2e61a5c303c6f13b165eac29e4be516316e1f26bae7d6cbdea1649258909a045",
          "sha256": "18e812b8a86522df26de6418f167e139d19e65b8a80bfdfba053d04e43daf050",
          "sha1": "97d1dac49ec0759c68f60b1a937a538647616d15",
          "md5": "b569a7402bddd6a9f2f98bea724ce514"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.kyori",
          "module": "adventure-bom",
          "version": {
            "requires": "4.17.0-SNAPSHOT"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "net.kyori",
          "module": "adventure-key",
          "version": {
            "requires": "4.17.0-SNAPSHOT"
          }
        },
        {
          "group": "net.kyori",
          "module": "examination-api",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "net.kyori",
          "module": "examination-string",
          "version": {
            "requires": "1.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "adventure-api-4.17.0-SNAPSHOT.jar",
          "url": "adventure-api-4.17.0-SNAPSHOT.jar",
          "size": 399820,
          "sha512": "5df8e5a3fa0f6c68a31c3bf0d9a8c3f766eb72da18f382aebcc9ce79fa895bfd2e61a5c303c6f13b165eac29e4be516316e1f26bae7d6cbdea1649258909a045",
          "sha256": "18e812b8a86522df26de6418f167e139d19e65b8a80bfdfba053d04e43daf050",
          "sha1": "97d1dac49ec0759c68f60b1a937a538647616d15",
          "md5": "b569a7402bddd6a9f2f98bea724ce514"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.kyori",
          "module": "adventure-bom",
          "version": {
            "requires": "4.17.0-SNAPSHOT"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "net.kyori",
          "module": "adventure-key",
          "version": {
            "requires": "4.17.0-SNAPSHOT"
          }
        },
        {
          "group": "net.kyori",
          "module": "examination-api",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "net.kyori",
          "module": "examination-string",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "24.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "adventure-api-4.17.0-SNAPSHOT-javadoc.jar",
          "url": "adventure-api-4.17.0-SNAPSHOT-javadoc.jar",
          "size": 812256,
          "sha512": "3c9d0ccf8275ce6398befb5cc98427c1229e12bbad93870353e291ce7dc4e2c7715f165c9d81a85740569c024ff7c96f65230e629abc00b810de6aa7f61e12ea",
          "sha256": "7757574eb343dd9c3067e183dbbb3c3e698cf25e24c7ea0658c7148b27e121f9",
          "sha1": "1e0d02b83f6791971bdd137c6d2137f6ec90fcbb",
          "md5": "11e598a9aa1b05f4f048e6a02916838d"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "adventure-api-4.17.0-SNAPSHOT-sources.jar",
          "url": "adventure-api-4.17.0-SNAPSHOT-sources.jar",
          "size": 318709,
          "sha512": "d338215a8a5bdcabd3103b3bfac63335baf26b593abe694206a52cab082a3993b23b7370082330b8c228f4c34c437e5ef17bb6a6bc58e546c67392219f728d74",
          "sha256": "05a80b2e54d1348ad02420c45da4c770efa01d8b6fffdb26b8f8ee66c79bebbc",
          "sha1": "9183471b9b7449c74c83e10afc2dc4aeb37753a7",
          "md5": "00b40229a29374b1bf0470892d24712e"
        }
      ]
    }
  ]
}
